  // ───────────────────────── more looks: skins, paint, eyes, teeth, rings, aims, trails, impacts, poles ─────────────────────────
  // Everything is drawn in code in the same inked, flat 1930s style, and every item keeps the same silhouette
  // (and the same physics). Skull art is in skull units: r = 1, the cranium roughly x −1…1, y −1.1…0.7.
  const seeded = (seed, n, fn) => { const rnd = mulberry32(seed); for (let i = 0; i < n; i++) fn(rnd, i); };
  const blob = (c, x, y, r, rnd, k = 0.3) => { c.beginPath(); for (let i = 0; i <= 8; i++) { const a = (i / 8) * TAU, rr2 = r * (1 - k / 2 + rnd() * k); i ? c.lineTo(x + Math.cos(a) * rr2, y + Math.sin(a) * rr2) : c.moveTo(x + Math.cos(a) * rr2, y + Math.sin(a) * rr2); } c.closePath(); };

  // ── skulls
  Object.assign(SKINS, {
    cookie: P("#D9A566", "#B98247", "#F2CC92", "#3A2410", "#2A190A", "#F2E7C9", null, {
      detail(c) { c.fillStyle = "#4A2A12"; seeded(11, 11, rnd => { blob(c, rnd() * 1.8 - 0.9, rnd() * 1.5 - 1.05, 0.07 + rnd() * 0.05, rnd, 0.5); c.fill(); }); c.fillStyle = "rgba(255,230,180,.35)"; seeded(12, 16, rnd => { c.beginPath(); c.arc(rnd() * 1.8 - 0.9, rnd() * 1.6 - 1.1, 0.015, 0, TAU); c.fill(); }); } }),
    cow: P("#F7F3EA", "#D8D2C4", "#FFFFFF", INK, INK, "#F7F1DF", null, {
      detail(c) { c.fillStyle = INK; for (const [x, y, r] of [[-0.55, -0.7, 0.26], [0.45, -0.85, 0.2], [0.72, -0.2, 0.18], [-0.8, 0.05, 0.14], [0.1, -1.0, 0.12]]) { blob(c, x, y, r, mulberry32((x * 100) | 0), 0.45); c.fill(); } },
      behind(c) { c.fillStyle = CREAM; c.strokeStyle = INK; c.lineWidth = 0.05; for (const sd of [-1, 1]) { c.beginPath(); c.moveTo(sd * 0.5, -0.92); c.quadraticCurveTo(sd * 0.85, -1.05, sd * 0.95, -1.3); c.quadraticCurveTo(sd * 0.7, -1.1, sd * 0.35, -1.0); c.closePath(); c.fill(); c.stroke(); } } }),
    marble: P("#EDEAE3", "#C9C4B8", "#FFFFFF", "#2B2A28", "#232220", "#EDEAE3", "rgba(40,40,40,.4)", {
      detail(c) { c.strokeStyle = "rgba(110,105,98,.45)"; c.lineWidth = 0.025; seeded(21, 6, rnd => { let x = rnd() * 2 - 1, y = -1.1; c.beginPath(); c.moveTo(x, y); for (let k = 0; k < 6; k++) { x += (rnd() - 0.5) * 0.4; y += 0.3; c.lineTo(x, y); } c.stroke(); }); } }),
    chocolate: P("#6B3E22", "#4E2B16", "#9A6440", "#1E0F06", "#170B04", "#F2E7C9", null, {
      detail(c) { c.strokeStyle = "#F4E6D0"; c.lineWidth = 0.05; c.beginPath(); for (let i = 0; i <= 12; i++) { const x = -0.9 + i * 0.15; c.lineTo(x, -0.62 + (i % 2 ? -0.12 : 0.05)); } c.stroke();
        c.fillStyle = "#8B5530"; c.beginPath(); c.moveTo(-1.2, -1.3); c.lineTo(1.2, -1.3); c.lineTo(1.2, -0.85); for (let x = 1.2; x > -1.2; x -= 0.24) c.quadraticCurveTo(x - 0.06, -0.62 - (Math.abs(x * 7) % 3) * 0.06, x - 0.24, -0.85); c.closePath(); c.fill(); } }),
    jawbreaker: P("#F2E7C9", "#D8C9A5", "#FFFFFF", INK, INK, "#F2E7C9", null, {
      detail(c, t) { const cols = ["#E8505B", "#F5B83A", "#5BB86A", "#4A8FD8", "#A06BC8", "#F2E7C9"]; for (let i = 7; i >= 0; i--) { c.fillStyle = cols[(i + Math.floor(t * 0.5)) % cols.length]; c.beginPath(); c.arc(0, -0.25, 0.2 + i * 0.16, 0, TAU); c.fill(); } } }),
    watermelon: P("#E8505B", "#C23A47", "#FF8A92", "#1C2A12", "#1C2A12", "#F2E7C9", null, {
      detail(c) { c.fillStyle = "#3E7A2E"; c.beginPath(); c.moveTo(-1.2, -1.3); c.lineTo(1.2, -1.3); c.lineTo(1.2, -0.8); c.quadraticCurveTo(0, -0.62, -1.2, -0.8); c.closePath(); c.fill(); c.fillStyle = "#F4F0D8"; c.beginPath(); c.moveTo(-1.2, -0.8); c.quadraticCurveTo(0, -0.62, 1.2, -0.8); c.lineTo(1.2, -0.72); c.quadraticCurveTo(0, -0.54, -1.2, -0.72); c.closePath(); c.fill();
        c.strokeStyle = "#285A1C"; c.lineWidth = 0.06; for (let x = -0.9; x <= 0.9; x += 0.3) { c.beginPath(); c.moveTo(x, -1.2); c.lineTo(x + 0.05, -0.78); c.stroke(); }
        c.fillStyle = INK; seeded(31, 12, rnd => { const x = rnd() * 1.6 - 0.8, y = rnd() * 0.9 - 0.45; c.beginPath(); c.ellipse(x, y, 0.03, 0.055, rnd() - 0.5, 0, TAU); c.fill(); }); } }),
    tiger: P("#E88A2E", "#B8641A", "#FFC07A", INK, INK, "#F2E7C9", null, {
      detail(c) { c.fillStyle = INK; for (const sd of [-1, 1]) for (let i = 0; i < 4; i++) { const y = -0.95 + i * 0.3; c.beginPath(); c.moveTo(sd * 1.1, y); c.quadraticCurveTo(sd * 0.7, y + 0.05, sd * (0.55 - i * 0.03), y + 0.12); c.quadraticCurveTo(sd * 0.75, y + 0.14, sd * 1.1, y + 0.16); c.closePath(); c.fill(); }
        c.beginPath(); c.moveTo(-0.1, -1.1); c.lineTo(0, -0.78); c.lineTo(0.1, -1.1); c.fill(); } }),
    zombie: P("#9DB08A", "#7A8C68", "#C4D4B0", "#1E2616", "#161C10", "#E8F0D8", "rgba(30,38,22,.7)", {
      detail(c) { c.strokeStyle = "#2A1A1A"; c.lineWidth = 0.035; c.beginPath(); c.moveTo(-0.7, -0.75); c.quadraticCurveTo(-0.2, -0.95, 0.35, -0.72); c.stroke(); for (let i = 0; i < 6; i++) { const k = i / 5, x = -0.7 + k * 1.05, y = -0.75 - Math.sin(k * Math.PI) * 0.12; c.beginPath(); c.moveTo(x - 0.03, y - 0.07); c.lineTo(x + 0.03, y + 0.07); c.stroke(); }
        c.fillStyle = "rgba(90,110,60,.5)"; c.beginPath(); c.ellipse(0.55, -0.3, 0.14, 0.09, 0.4, 0, TAU); c.fill(); },
      behind(c) { c.fillStyle = "#8E949F"; c.strokeStyle = INK; c.lineWidth = 0.04; for (const sd of [-1, 1]) { c.beginPath(); rr(c, sd * 1.02 - 0.08, -0.25, 0.16, 0.2, 0.04); c.fill(); c.stroke(); } } }),
    snowman: P("#F4F8FB", "#CFDCE6", "#FFFFFF", "#1E2A33", "#1A242C", "#F4F8FB", null, {
      top(c) { c.fillStyle = "#E8893A"; c.strokeStyle = INK; c.lineWidth = 0.04; c.beginPath(); c.moveTo(-0.07, -0.08); c.lineTo(0.55, 0.05); c.lineTo(-0.06, 0.1); c.closePath(); c.fill(); c.stroke(); c.strokeStyle = "rgba(0,0,0,.25)"; c.beginPath(); c.moveTo(0.12, -0.02); c.lineTo(0.14, 0.07); c.moveTo(0.28, 0.01); c.lineTo(0.3, 0.06); c.stroke(); } }),
    moon: P("#C9C6BC", "#9E9A8E", "#E8E6DE", "#2A2822", "#1E1C18", "#E8E6DE", null, {
      detail(c) { seeded(41, 9, rnd => { const x = rnd() * 1.8 - 0.9, y = rnd() * 1.5 - 1.05, r = 0.05 + rnd() * 0.1; c.fillStyle = "rgba(90,86,76,.45)"; c.beginPath(); c.arc(x, y, r, 0, TAU); c.fill(); c.strokeStyle = "rgba(240,238,230,.5)"; c.lineWidth = 0.02; c.beginPath(); c.arc(x, y, r, Math.PI * 0.2, Math.PI * 0.9); c.stroke(); }); } }),
    glow: P("#D8F6C0", "#A8D890", "#F4FFE8", "#1C3316", "#12240E", "#EFFFE0", null, {
      behind(c, t) { const k = 0.55 + 0.25 * Math.sin(t * 3); const g = c.createRadialGradient(0, -0.2, 0.6, 0, -0.2, 1.7); g.addColorStop(0, `rgba(170,255,120,${0.45 * k})`); g.addColorStop(1, "rgba(170,255,120,0)"); c.fillStyle = g; c.beginPath(); c.arc(0, -0.2, 1.7, 0, TAU); c.fill(); } }),
    robot: P("#B8C2CC", "#8A96A2", "#EEF3F8", "#1A2129", "#10161C", "#FF5A4A", null, {
      detail(c) { c.strokeStyle = "rgba(26,33,41,.5)"; c.lineWidth = 0.03; c.beginPath(); c.moveTo(-1, -0.6); c.lineTo(1, -0.6); c.moveTo(0, -1.2); c.lineTo(0, -0.6); c.stroke(); c.fillStyle = "#6A7682"; for (const [x, y] of [[-0.8, -0.5], [0.8, -0.5], [-0.12, -0.7], [0.12, -0.7], [-0.75, 0.2], [0.75, 0.2]]) { c.beginPath(); c.arc(x, y, 0.035, 0, TAU); c.fill(); } },
      top(c, t) { c.strokeStyle = INK; c.lineWidth = 0.05; c.beginPath(); c.moveTo(0, -1.02); c.lineTo(0, -1.38); c.stroke(); c.fillStyle = (t % 1.2) < 0.6 ? "#FF5A4A" : "#7A2A22"; c.beginPath(); c.arc(0, -1.42, 0.08, 0, TAU); c.fill(); c.stroke(); } }),
    mummy: P("#E6DCC2", "#BFB28E", "#F8F2E0", "#3A3022", "#2A2218", "#F8F2E0", null, {
      detail(c) { c.strokeStyle = "rgba(58,48,34,.55)"; c.lineWidth = 0.03; for (let i = 0; i < 9; i++) { const y = -1.12 + i * 0.2; c.beginPath(); c.moveTo(-1.1, y + (i % 2 ? 0.06 : -0.04)); c.lineTo(1.1, y - (i % 2 ? 0.05 : -0.07)); c.stroke(); } c.fillStyle = "rgba(160,140,100,.25)"; c.fillRect(-1.1, -0.45, 2.2, 0.12); },
      top(c, t) { c.save(); c.translate(0.72, -0.72); c.rotate(0.3 + Math.sin(t * 5) * 0.2); c.fillStyle = "#E6DCC2"; c.strokeStyle = "#3A3022"; c.lineWidth = 0.035; c.beginPath(); c.moveTo(0, 0); c.quadraticCurveTo(0.25, 0.1, 0.45, -0.05); c.lineTo(0.45, 0.08); c.quadraticCurveTo(0.25, 0.22, 0, 0.12); c.closePath(); c.fill(); c.stroke(); c.restore(); } }),
    blueprint: P("#2F5C9A", "#244A7E", "#6A94CC", "#E8F0FF", "#16304F", "#E8F0FF", null, {
      detail(c) { c.strokeStyle = "rgba(232,240,255,.22)"; c.lineWidth = 0.015; for (let x = -1.1; x < 1.1; x += 0.15) { c.beginPath(); c.moveTo(x, -1.3); c.lineTo(x, 1); c.stroke(); } for (let y = -1.2; y < 1; y += 0.15) { c.beginPath(); c.moveTo(-1.2, y); c.lineTo(1.2, y); c.stroke(); }
        c.strokeStyle = "rgba(232,240,255,.7)"; c.lineWidth = 0.025; c.beginPath(); c.moveTo(-0.8, -0.95); c.lineTo(0.8, -0.95); c.moveTo(-0.8, -1.0); c.lineTo(-0.8, -0.9); c.moveTo(0.8, -1.0); c.lineTo(0.8, -0.9); c.stroke(); c.fillStyle = "rgba(232,240,255,.8)"; c.font = "0.14px sans-serif"; c.textAlign = "center"; c.fillText("R=1", 0, -1.0); } }),
    neon: P("#1C1428", "#140E1E", "#3A2A50", "#FF4FB8", "#0A0710", "#7FF6FF", null, { flat: true,
      flick: t => ((t % 4.1) < 0.07 || ((t % 4.1) > 0.16 && (t % 4.1) < 0.2) ? P("#1C1428", "#140E1E", "#3A2A50", "#6A2A50", "#0A0710", "#3A7A80", null, { flat: true }) : null),
      behind(c) { const g = c.createRadialGradient(0, -0.2, 0.7, 0, -0.2, 1.6); g.addColorStop(0, "rgba(255,79,184,.35)"); g.addColorStop(1, "rgba(255,79,184,0)"); c.fillStyle = g; c.beginPath(); c.arc(0, -0.2, 1.6, 0, TAU); c.fill(); } }),
    ghostly: P("rgba(235,245,250,.55)", "rgba(190,210,225,.45)", "rgba(255,255,255,.8)", "rgba(30,40,60,.75)", "rgba(20,26,40,.72)", "#FFFFFF", null, {
      behind(c, t) { c.fillStyle = "rgba(235,245,250,.18)"; c.beginPath(); c.moveTo(-0.8, 0.4); for (let i = 0; i <= 6; i++) { const x = -0.8 + i * 0.27; c.quadraticCurveTo(x - 0.13, 1.1 + Math.sin(t * 4 + i) * 0.08, x, 0.6); } c.lineTo(0.8, 0.4); c.closePath(); c.fill(); } }),
    onyx: P("#2A2530", "#1C1822", "#5A4E6A", "#0A080C", "#08060A", "#D8C8F0", null, {
      detail(c, t) { const k = ((t * 0.25) % 2.4) - 1.2; c.fillStyle = "rgba(190,150,255,.2)"; c.beginPath(); c.moveTo(k - 0.1, -1.3); c.lineTo(k + 0.15, -1.3); c.lineTo(k - 0.45, 0.8); c.lineTo(k - 0.7, 0.8); c.fill(); },
      top(c, t) { glintAt(c, -0.45, -0.72, Math.pow(Math.max(0, Math.sin(t * 1.7)), 14)); } }),
    lava: P("#3A2A26", "#2A1C18", "#5A4640", "#120A08", "#1A0A04", "#FFB040", null, {
      detail(c, t) { c.save(); c.globalCompositeOperation = "lighter"; const k = 0.6 + 0.4 * Math.sin(t * 2.3); c.strokeStyle = `rgba(255,${120 + 60 * k},40,${0.75 * k + 0.25})`; c.lineWidth = 0.05;
        seeded(51, 5, rnd => { let x = rnd() * 1.6 - 0.8, y = -1.1; c.beginPath(); c.moveTo(x, y); for (let j = 0; j < 5; j++) { x += (rnd() - 0.5) * 0.45; y += 0.28; c.lineTo(x, y); } c.stroke(); }); c.restore(); },
      behind(c, t) { flameTongues(c, t, 5, 1.2, -0.7, ["rgba(232,137,58,.8)", "rgba(169,67,50,.8)"]); } }),
    cracked: P("#F2EAD6", "#D4C6A6", "#FFFDF6", "#1A1510", "#141008", "#F2EAD6", "rgba(26,21,16,.9)", {
      detail(c) { c.strokeStyle = "rgba(26,21,16,.8)"; c.lineWidth = 0.035; for (const pts of [[[-0.6, -1.05], [-0.5, -0.8], [-0.62, -0.62], [-0.48, -0.45]], [[0.75, -0.6], [0.55, -0.5], [0.6, -0.3]], [[0.05, -1.1], [0.12, -0.95], [0.02, -0.85]]]) { c.beginPath(); pts.forEach(([x, y], k) => k ? c.lineTo(x, y) : c.moveTo(x, y)); c.stroke(); } },
      top(c) { c.save(); c.translate(-0.4, -0.78); for (const a of [0.7, -0.7]) { c.save(); c.rotate(a); c.fillStyle = "#E8D8B4"; c.strokeStyle = "#3A2D1C"; c.lineWidth = 0.03; c.beginPath(); rr(c, -0.3, -0.07, 0.6, 0.14, 0.03); c.fill(); c.stroke(); c.restore(); } c.restore(); } }),
    harvest: P("#E8B84A", "#B8862A", "#FFE9A0", "#3A2604", "#2A1B04", "#3A2604", null, {
      detail(c) { c.strokeStyle = "rgba(120,80,10,.5)"; c.lineWidth = 0.05; for (const x of [-0.55, -0.2, 0.2, 0.55]) { c.beginPath(); c.moveTo(x * 0.7, -1.08); c.quadraticCurveTo(x * 1.35, -0.2, x * 0.9, 0.9); c.stroke(); } },
      eyes(c, s, i, t, f, pal, eyes) { const g = c.createRadialGradient(s.x, s.y + 0.05, 0.02, s.x, s.y, s.ry * 1.1); g.addColorStop(0, "rgba(255,250,200,.95)"); g.addColorStop(1, "rgba(220,150,20,.9)"); c.fillStyle = g; c.fillRect(s.x - 0.5, s.y - 0.5, 1, 1); drawPupil(c, eyes, s, i, t, f, pal); },
      top(c, t) { c.fillStyle = "#5A6B2A"; c.strokeStyle = INK; c.lineWidth = 0.04; c.beginPath(); c.moveTo(-0.06, -1.04); c.quadraticCurveTo(-0.02, -1.26, 0.14, -1.3); c.lineTo(0.16, -1.22); c.quadraticCurveTo(0.06, -1.18, 0.07, -1.04); c.closePath(); c.fill(); c.stroke(); glintAt(c, -0.5, -0.7, Math.pow(Math.max(0, Math.sin(t * 2)), 12)); } }),
    disco: P("#C8CCD4", "#8E949F", "#FFFFFF", INK, "#15181E", "#FFFFFF", null, {
      detail(c, t) { const n = 0.16, cols = ["#E8505B", "#5BC8E8", "#F5D84A", "#B86BE8", "#FFFFFF"]; for (let y = -1.2; y < 0.8; y += n) for (let x = -1.1; x < 1.1; x += n) { const k = Math.sin(x * 9 + y * 7 + t * 4); c.fillStyle = k > 0.8 ? cols[Math.abs(((x * 13 + y * 7) | 0)) % cols.length] : k > 0 ? "#DDE1E8" : "#9EA4AE"; c.fillRect(x + 0.01, y + 0.01, n - 0.02, n - 0.02); } },
      top(c, t) { for (let i = 0; i < 3; i++) glintAt(c, Math.sin(t + i * 2) * 0.7, -0.8 + i * 0.3, Math.pow(Math.max(0, Math.sin(t * 3 + i * 2.1)), 8)); } }),
    bubblegum: P("#F59AC4", "#D96FA3", "#FFD0E6", "#4A1830", "#3A1026", "#FFE8F2", null, {
      jawTop(c, t, drop, pal, bottom) { const cyc = t % 4, k = cyc < 2.6 ? cyc / 2.6 : cyc < 2.75 ? 1 : 0; if (k <= 0.05) return; const r = 0.1 + k * 0.42; c.fillStyle = "rgba(255,150,200,.85)"; c.strokeStyle = "#4A1830"; c.lineWidth = 0.035; c.beginPath(); c.arc(0.05, bottom - 0.28 + r * 0.7, r, 0, TAU); c.fill(); c.stroke(); c.fillStyle = "rgba(255,255,255,.7)"; c.beginPath(); c.ellipse(-0.05 - r * 0.3, bottom - 0.28 + r * 0.4, r * 0.18, r * 0.1, -0.6, 0, TAU); c.fill(); } }),
    stained: P("#3A3348", "#2A2436", "#6A5A80", "#141018", "#141018", "#FFF4C8", null, {
      detail(c, t) { const cols = ["rgba(220,70,70,.85)", "rgba(70,130,220,.85)", "rgba(240,200,60,.85)", "rgba(80,180,110,.85)", "rgba(170,90,210,.85)"]; let k = 0;
        for (let y = -1.2; y < 0.8; y += 0.34) for (let x = -1.1 + ((y * 10) % 2 ? 0.17 : 0); x < 1.1; x += 0.34) { c.fillStyle = cols[k++ % cols.length]; c.beginPath(); c.moveTo(x, y); c.lineTo(x + 0.34, y + 0.05); c.lineTo(x + 0.3, y + 0.36); c.lineTo(x - 0.03, y + 0.32); c.closePath(); c.fill(); c.strokeStyle = "#141018"; c.lineWidth = 0.05; c.stroke(); }
        c.save(); c.globalCompositeOperation = "lighter"; c.fillStyle = `rgba(255,240,200,${0.12 + 0.08 * Math.sin(t * 2)})`; c.fillRect(-1.2, -1.3, 2.4, 2.6); c.restore(); } })
  });

  // ── paint jobs
  const PAINTS = {
    racing(c) { c.fillStyle = RED; c.fillRect(-0.16, -1.3, 0.32, 2.6); c.fillStyle = CREAM; c.fillRect(-0.21, -1.3, 0.04, 2.6); c.fillRect(0.17, -1.3, 0.04, 2.6); },
    zebra(c) { c.fillStyle = INK; for (let i = -6; i <= 6; i++) { const x = i * 0.2; c.beginPath(); c.moveTo(x - 0.05, -1.3); c.quadraticCurveTo(x + 0.12, -0.6, x - 0.02, 0.8); c.lineTo(x + 0.05, 0.8); c.quadraticCurveTo(x + 0.2, -0.6, x + 0.04, -1.3); c.closePath(); c.fill(); } },
    tartan(c) { for (const [col, w, step, off] of [["rgba(169,67,50,.75)", 0.22, 0.5, 0], ["rgba(38,54,74,.55)", 0.1, 0.5, 0.25], ["rgba(242,231,201,.5)", 0.03, 0.25, 0.1]]) { c.fillStyle = col; for (let v = -1.3 + off; v < 1; v += step) { c.fillRect(-1.2, v, 2.4, w); c.fillRect(v, -1.3, w, 2.6); } } },
    leopard(c) { seeded(61, 22, rnd => { const x = rnd() * 2 - 1, y = rnd() * 1.7 - 1.15; c.fillStyle = "#C9832A"; blob(c, x, y, 0.08, rnd, 0.5); c.fill(); c.strokeStyle = INK; c.lineWidth = 0.035; c.beginPath(); c.arc(x, y, 0.09, 0.3, 2.2); c.stroke(); c.beginPath(); c.arc(x, y, 0.09, 3.2, 5); c.stroke(); }); },
    camo(c) { for (const [col, n, seed] of [["#5E6B3A", 9, 71], ["#3A4226", 8, 72], ["#8A7A4E", 7, 73]]) { c.fillStyle = col; seeded(seed, n, rnd => { blob(c, rnd() * 2 - 1, rnd() * 1.8 - 1.2, 0.18 + rnd() * 0.12, rnd, 0.6); c.fill(); }); } },
    argyle(c) { for (let y = -1.3, r = 0; y < 0.9; y += 0.36, r++) for (let x = -1.2 + (r % 2) * 0.22; x < 1.2; x += 0.44) { c.fillStyle = r % 2 ? "rgba(53,107,104,.7)" : "rgba(169,67,50,.7)"; c.beginPath(); c.moveTo(x, y); c.lineTo(x + 0.22, y + 0.18); c.lineTo(x, y + 0.36); c.lineTo(x - 0.22, y + 0.18); c.closePath(); c.fill(); }
      c.strokeStyle = "rgba(23,19,15,.6)"; c.lineWidth = 0.015; for (let k = -3; k < 6; k++) { c.beginPath(); c.moveTo(-1.2 + k * 0.44, -1.3); c.lineTo(-1.2 + k * 0.44 + 1.3, 0.9); c.moveTo(1.2 - k * 0.44, -1.3); c.lineTo(1.2 - k * 0.44 - 1.3, 0.9); c.stroke(); } },
    barber(c, t) { c.fillStyle = RED; for (let k = -10; k < 10; k++) { const x = k * 0.36 + (t * 0.3) % 0.36; c.beginPath(); c.moveTo(x, -1.3); c.lineTo(x + 0.16, -1.3); c.lineTo(x + 0.16 + 1.2, 0.9); c.lineTo(x + 1.2, 0.9); c.closePath(); c.fill(); } c.fillStyle = "#3A5BA0"; c.fillRect(-1.2, -1.3, 2.4, 0.14); },
    harlequin(c) { for (let y = -1.3, r = 0; y < 0.9; y += 0.3, r++) for (let x = -1.2, q = 0; x < 1.2; x += 0.3, q++) { if ((r + q) % 2) continue; c.fillStyle = (r + q) % 4 ? "rgba(169,67,50,.8)" : "rgba(23,19,15,.75)"; c.beginPath(); c.moveTo(x + 0.15, y); c.lineTo(x + 0.3, y + 0.15); c.lineTo(x + 0.15, y + 0.3); c.lineTo(x, y + 0.15); c.closePath(); c.fill(); } },
    sprinkles(c) { const cols = [RED, TEAL, MUSTARD, "#E88AB8", "#7FC8E8", CREAM]; seeded(81, 40, (rnd, i) => { c.save(); c.translate(rnd() * 2.1 - 1.05, rnd() * 1.8 - 1.2); c.rotate(rnd() * TAU); c.fillStyle = cols[i % cols.length]; c.beginPath(); rr(c, -0.06, -0.018, 0.12, 0.036, 0.018); c.fill(); c.restore(); }); },
    bolt(c) { c.fillStyle = MUSTARD; c.strokeStyle = INK; c.lineWidth = 0.04; c.beginPath(); c.moveTo(0.15, -1.2); c.lineTo(-0.3, -0.55); c.lineTo(-0.02, -0.55); c.lineTo(-0.2, 0.1); c.lineTo(0.35, -0.72); c.lineTo(0.06, -0.72); c.lineTo(0.3, -1.2); c.closePath(); c.fill(); c.stroke(); },
    flames(c, t) { c.strokeStyle = INK; c.lineWidth = 0.04; for (const [col, sc] of [[RED, 1], [EMBER, 0.78], [MUSTARD, 0.55]]) { c.fillStyle = col; c.beginPath(); c.moveTo(-1.2, -1.3); c.lineTo(1.2, -1.3); for (let i = 0; i <= 6; i++) { const x = 1.2 - i * 0.4, tip = -1.3 + (0.95 + 0.12 * Math.sin(t * 5 + i)) * sc + 0.15; c.quadraticCurveTo(x - 0.05, tip - 0.1, x - 0.2, tip + 0.15); c.quadraticCurveTo(x - 0.25, tip - 0.3, x - 0.4, -1.3 + 0.35 * sc); } c.closePath(); c.fill(); if (col === RED) c.stroke(); } },
    rainbow(c) { const cols = ["#E8505B", "#F58A3A", "#F5D84A", "#5BB86A", "#4A8FD8", "#8A6BC8"]; cols.forEach((col, i) => { c.strokeStyle = col; c.lineWidth = 0.13; c.beginPath(); c.arc(0, 0.6, 1.5 - i * 0.13, Math.PI, TAU); c.stroke(); }); },
    circuit(c) { c.fillStyle = "rgba(40,110,60,.55)"; c.fillRect(-1.2, -1.3, 2.4, 2.6); c.strokeStyle = "#C9A64A"; c.lineWidth = 0.03; seeded(91, 9, rnd => { let x = rnd() * 2 - 1, y = rnd() * 1.6 - 1.2; c.beginPath(); c.moveTo(x, y); for (let k = 0; k < 3; k++) { if (k % 2) x += (rnd() - 0.5) * 0.8; else y += (rnd() - 0.3) * 0.6; c.lineTo(x, y); } c.stroke(); c.fillStyle = "#C9A64A"; c.beginPath(); c.arc(x, y, 0.04, 0, TAU); c.fill(); }); },
    marigold(c) { const pts = [[-0.55, -0.8], [0, -1.0], [0.55, -0.78], [-0.8, -0.3], [0.8, -0.28], [0, -0.62]]; pts.forEach(([x, y], i) => { for (let k = 0; k < 10; k++) { const a = (k / 10) * TAU; c.fillStyle = k % 2 ? "#F58A3A" : "#F5B83A"; c.beginPath(); c.ellipse(x + Math.cos(a) * 0.08, y + Math.sin(a) * 0.08, 0.075, 0.04, a, 0, TAU); c.fill(); } c.fillStyle = "#A94332"; c.beginPath(); c.arc(x, y, 0.045, 0, TAU); c.fill(); });
      c.strokeStyle = "#356B68"; c.lineWidth = 0.03; for (const s of SOCK) { c.beginPath(); c.arc(s.x, s.y, s.rx + 0.1, 0, TAU); c.stroke(); for (let k = 0; k < 8; k++) { const a = (k / 8) * TAU; c.beginPath(); c.arc(s.x + Math.cos(a) * (s.rx + 0.16), s.y + Math.sin(a) * (s.ry + 0.16), 0.03, 0, TAU); c.stroke(); } } },
    galaxy(c, t) { const g = c.createLinearGradient(-1, -1.2, 1, 0.8); g.addColorStop(0, "rgba(40,20,90,.85)"); g.addColorStop(0.5, "rgba(120,40,140,.75)"); g.addColorStop(1, "rgba(20,40,110,.85)"); c.fillStyle = g; c.fillRect(-1.2, -1.3, 2.4, 2.6);
      seeded(101, 30, rnd => { const x = rnd() * 2.2 - 1.1, y = rnd() * 2 - 1.2, tw = 0.5 + 0.5 * Math.sin(t * 3 + x * 9); c.fillStyle = `rgba(255,255,255,${0.4 + 0.6 * tw})`; c.beginPath(); c.arc(x, y, 0.012 + rnd() * 0.02, 0, TAU); c.fill(); }); c.fillStyle = MUSTARD; star(c, 0.5, -0.8, 0.08, 4, 0.3, t); c.fill(); },
    tiretracks(c) { c.fillStyle = "rgba(23,19,15,.7)"; for (const off of [-0.35, 0.35]) for (let y = -1.3; y < 0.9; y += 0.12) { c.save(); c.translate(off + y * 0.25, y); c.rotate(0.25); c.fillRect(-0.14, 0, 0.28, 0.05); c.restore(); } },
    eightball(c) { c.fillStyle = "rgba(23,19,15,.92)"; c.fillRect(-1.2, -1.3, 2.4, 2.6); c.fillStyle = "#FBF9F4"; c.beginPath(); c.arc(0, -0.72, 0.28, 0, TAU); c.fill(); c.fillStyle = INK; c.font = "bold 0.36px sans-serif"; c.textAlign = "center"; c.textBaseline = "middle"; c.fillText("8", 0, -0.7); }
  };
  Object.assign(PAINT_ON_JAW, { zebra: 1, tartan: 1, leopard: 1, camo: 1, harlequin: 1, galaxy: 1, eightball: 1, sprinkles: 1 });

  // ── eyes (what sits in the sockets)
  const EYES_X = {
    googly(c, px, py, rp, s, i, t) { c.fillStyle = "#FBF9F4"; c.beginPath(); c.arc(s.x, s.y, s.rx * 0.8, 0, TAU); c.fill(); const a = t * (i ? 7 : -9) + i, d = s.rx * 0.38; c.fillStyle = INK; c.beginPath(); c.arc(s.x + Math.cos(a) * d * 0.4, s.y + Math.abs(Math.sin(a)) * d, s.rx * 0.36, 0, TAU); c.fill(); },
    cat(c, px, py, rp, s, i, t, f) { c.fillStyle = "#E8C83A"; c.beginPath(); c.ellipse(px, py, rp * 0.95, rp * 1.25, 0, 0, TAU); c.fill(); c.fillStyle = INK; c.beginPath(); c.ellipse(px, py, rp * (0.15 + 0.25 * (f.pupil - 0.4)), rp * 1.1, 0, 0, TAU); c.fill(); },
    shifty(c, px, py, rp, s, i, t, f, pal) { const k = Math.sin(t * 1.3) > 0 ? 1 : -1; c.fillStyle = pal.pupil; c.beginPath(); c.ellipse(s.x + k * s.rx * 0.45, py, rp * 0.7, rp * 0.9, 0, 0, TAU); c.fill(); c.fillStyle = pal.base; c.fillRect(s.x - 1, s.y - 1.4, 2, (s.y - s.ry * 0.25) - (s.y - 1.4)); },
    moons(c, px, py, rp, s, i, t, f, pal) { c.fillStyle = "#F5D84A"; c.beginPath(); c.arc(px, py, rp * 1.05, 0, TAU); c.fill(); c.fillStyle = pal.socket; c.beginPath(); c.arc(px + rp * 0.45, py - rp * 0.2, rp * 0.9, 0, TAU); c.fill(); },
    clover(c, px, py, rp, s, i, t) { c.save(); c.translate(px, py); c.rotate(t * 0.8 * (i ? 1 : -1)); c.fillStyle = "#5BB86A"; for (let k = 0; k < 4; k++) { c.rotate(Math.PI / 2); c.beginPath(); c.arc(-rp * 0.35, -rp * 0.42, rp * 0.42, 0, TAU); c.arc(rp * 0.35, -rp * 0.42, rp * 0.42, 0, TAU); c.fill(); } c.restore(); },
    led(c, px, py, rp, s, i, t) { const on = 0.7 + 0.3 * Math.sin(t * 10); const g = c.createRadialGradient(px, py, 0, px, py, rp * 2.2); g.addColorStop(0, `rgba(255,70,50,${on})`); g.addColorStop(1, "rgba(255,70,50,0)"); c.fillStyle = g; c.fillRect(px - rp * 2.2, py - rp * 2.2, rp * 4.4, rp * 4.4); c.fillStyle = "#FFD0C8"; c.beginPath(); c.arc(px, py, rp * 0.45, 0, TAU); c.fill(); c.fillStyle = "rgba(255,90,74,.35)"; c.fillRect(s.x - s.rx, py - 0.012 + Math.sin(t * 6) * s.ry * 0.5, s.rx * 2, 0.024); },
    bloodshot(c, px, py, rp, s) { c.fillStyle = "#FBF4EE"; c.beginPath(); c.arc(s.x, s.y + 0.02, s.rx * 0.78, 0, TAU); c.fill(); c.strokeStyle = "#D0443A"; c.lineWidth = 0.018; for (let k = 0; k < 6; k++) { const a = k * 1.05 + 0.3; c.beginPath(); c.moveTo(s.x + Math.cos(a) * s.rx * 0.78, s.y + Math.sin(a) * s.rx * 0.78); c.lineTo(s.x + Math.cos(a + 0.2) * s.rx * 0.45, s.y + Math.sin(a + 0.2) * s.rx * 0.45); c.stroke(); } c.fillStyle = "#356B68"; c.beginPath(); c.arc(px, py, rp * 0.75, 0, TAU); c.fill(); c.fillStyle = INK; c.beginPath(); c.arc(px, py, rp * 0.38, 0, TAU); c.fill(); },
    fire(c, px, py, rp, s, i, t) { c.save(); c.globalCompositeOperation = "lighter"; for (let k = 0; k < 3; k++) { const h = rp * (2.2 + 0.6 * Math.sin(t * 9 + k * 2 + i)), w = rp * (1.1 - k * 0.25); c.fillStyle = ["rgba(232,90,40,.8)", "rgba(245,160,50,.8)", "rgba(255,230,140,.9)"][k]; c.beginPath(); c.moveTo(px - w, py + rp * 0.8); c.quadraticCurveTo(px - w * 1.1, py - h * 0.3, px + Math.sin(t * 7 + k) * rp * 0.3, py - h); c.quadraticCurveTo(px + w * 1.1, py - h * 0.3, px + w, py + rp * 0.8); c.closePath(); c.fill(); } c.restore(); },
    sparkle(c, px, py, rp, s, i, t, f, pal) { c.fillStyle = pal.pupil; c.beginPath(); c.ellipse(px, py, rp * 1.05, rp * 1.25, 0, 0, TAU); c.fill(); c.fillStyle = pal.socket; c.beginPath(); c.ellipse(px, py + rp * 0.15, rp * 0.6, rp * 0.8, 0, 0, TAU); c.fill(); c.fillStyle = "#FFFFFF"; star(c, px - rp * 0.35, py - rp * 0.45, rp * 0.45 * (0.8 + 0.3 * Math.sin(t * 6 + i)), 4, 0.3, 0); c.fill(); c.beginPath(); c.arc(px + rp * 0.3, py + rp * 0.35, rp * 0.14, 0, TAU); c.fill(); },
    tears(c, px, py, rp, s, i, t, f, pal) { c.fillStyle = pal.pupil; c.beginPath(); c.ellipse(px, py, rp * 0.8, rp, 0, 0, TAU); c.fill(); const ph = (t * 1.2 + i * 0.5) % 1, ty = s.y + s.ry * (0.4 + ph * 0.9); c.fillStyle = "#7FC8E8"; c.beginPath(); c.moveTo(px + rp * 0.4, ty - rp * 0.5); c.quadraticCurveTo(px + rp * 0.9, ty + rp * 0.2, px + rp * 0.4, ty + rp * 0.35); c.quadraticCurveTo(px - rp * 0.1, ty + rp * 0.2, px + rp * 0.4, ty - rp * 0.5); c.fill(); },
    question(c, px, py, rp, s, i, t, f, pal) { c.save(); c.translate(px, py); c.rotate(Math.sin(t * 3 + i) * 0.2); c.fillStyle = pal.pupil; c.font = `900 ${rp * 3}px ${UIFONT}`; c.textAlign = "center"; c.textBaseline = "middle"; c.fillText("?", 0, rp * 0.2); c.restore(); },
    target(c, px, py, rp) { c.strokeStyle = "#E8505B"; c.lineWidth = 0.035; c.beginPath(); c.arc(px, py, rp * 1.1, 0, TAU); c.moveTo(px + rp * 0.5, py); c.arc(px, py, rp * 0.5, 0, TAU); c.moveTo(px - rp * 1.6, py); c.lineTo(px + rp * 1.6, py); c.moveTo(px, py - rp * 1.6); c.lineTo(px, py + rp * 1.6); c.stroke(); },
    diamond(c, px, py, rp, s, i, t) { c.save(); c.translate(px, py); c.fillStyle = "#BFEFFF"; c.strokeStyle = "#3A7A9A"; c.lineWidth = 0.02; c.beginPath(); c.moveTo(-rp, -rp * 0.3); c.lineTo(-rp * 0.5, -rp * 0.9); c.lineTo(rp * 0.5, -rp * 0.9); c.lineTo(rp, -rp * 0.3); c.lineTo(0, rp * 1.1); c.closePath(); c.fill(); c.stroke(); c.beginPath(); c.moveTo(-rp, -rp * 0.3); c.lineTo(rp, -rp * 0.3); c.moveTo(-rp * 0.3, -rp * 0.3); c.lineTo(0, rp * 1.1); c.lineTo(rp * 0.3, -rp * 0.3); c.stroke(); glintAt(c, -rp * 0.3, -rp * 0.5, Math.pow(Math.max(0, Math.sin(t * 3 + i)), 6) * 0.4); c.restore(); }
  };

  // ── teeth: return true when handled (edges: the gaps between teeth; seg(i, fn) clips to one tooth)
  const TEETH_X = {
    braces(c, T) { T.draw(); c.strokeStyle = "#9AA4AE"; c.lineWidth = 14; c.beginPath(); c.moveTo(T.box.x0 + 10, T.mid); c.lineTo(T.box.x1 - 10, T.mid); c.stroke(); c.fillStyle = "#C8D0D8"; c.strokeStyle = T.pal.line; c.lineWidth = 5; for (let i = 0; i < T.n; i++) { const x = (T.edges[i] + T.edges[i + 1]) / 2; c.beginPath(); rr(c, x - 14, T.mid - 14, 28, 28, 5); c.fill(); c.stroke(); } return true; },
    bucktooth(c, T) { T.draw(); if (!T.upper) return true; const i = Math.floor(T.n / 2) - 1, x0 = T.edges[i], x1 = T.edges[i + 2]; c.fillStyle = T.tooth; c.strokeStyle = T.pal.line; c.lineWidth = Math.max(10, T.minW); c.beginPath(); rr(c, x0 - 6, T.box.y0, x1 - x0 + 12, T.box.y1 - T.box.y0 + 70, 18); c.fill(); c.stroke(); c.beginPath(); c.moveTo((x0 + x1) / 2, T.box.y0 + 10); c.lineTo((x0 + x1) / 2, T.box.y1 + 60); c.stroke(); return true; },
    gap(c, T) { for (let i = 0; i < T.n; i++) if (!(T.upper && i === Math.floor(T.n / 2))) T.seg(i, () => T.draw()); return true; },
    piano(c, T) { for (let i = 0; i < T.n; i++) T.seg(i, () => T.draw(i % 2 && T.upper ? "#1A1A1A" : "#FBF9F4")); return true; },
    shark(c, T) { c.fillStyle = T.tooth; c.strokeStyle = T.pal.line; c.lineWidth = Math.max(8, T.minW); for (let i = 0; i < T.n; i++) { const a = T.edges[i], b = T.edges[i + 1], base = T.upper ? T.box.y0 : T.box.y1, tip = T.upper ? T.box.y1 + 25 : T.box.y0 - 25; c.beginPath(); c.moveTo(a, base); c.lineTo(b, base); c.lineTo((a + b) / 2, tip); c.closePath(); c.fill(); c.stroke(); } return true; },
    candycorn(c, T) { for (let i = 0; i < T.n; i++) T.seg(i, () => { T.draw("#F58A3A"); const h = T.box.y1 - T.box.y0; c.fillStyle = "#F5D84A"; c.fillRect(T.edges[i], T.upper ? T.box.y0 + h * 0.62 : T.box.y0, T.edges[i + 1] - T.edges[i], h * 0.38); c.fillStyle = "#FBF9F4"; c.fillRect(T.edges[i], T.upper ? T.box.y0 + h * 0.85 : T.box.y0, T.edges[i + 1] - T.edges[i], h * 0.15); }); return true; },
    grill(c, T) { T.draw(GOLD); c.fillStyle = "rgba(255,246,208,.8)"; for (let i = 0; i < T.n; i++) c.fillRect(T.edges[i] + 8, T.box.y0 + 8, 7, (T.box.y1 - T.box.y0) * 0.4); return true; },
    rotten(c, T) { for (let i = 0; i < T.n; i++) { if (i % 3 === 1 && T.upper) continue; T.seg(i, () => T.draw(i % 2 ? "#B8A868" : "#D8C890")); } c.fillStyle = "rgba(80,110,40,.6)"; c.beginPath(); c.arc(T.edges[1] + 20, T.mid, 12, 0, TAU); c.fill(); return true; },
    diamond(c, T) { T.draw("#D8F4FF"); c.fillStyle = "rgba(255,255,255,.9)"; for (let i = 0; i < T.n; i++) { const x = (T.edges[i] + T.edges[i + 1]) / 2; star(c, x, T.mid, 14, 4, 0.3, 0); c.fill(); } return true; }
  };

  // ── rings
  Object.assign(RINGS, {
    rope:     { style: "rope",    color: "#C8A46A", rgb: "200,164,106", shade: "rgba(60,40,10,.5)",  hi: "rgba(255,240,200,.6)" },
    tire:     { style: "tire",    color: "#2A2A2E", rgb: "120,120,130", shade: "rgba(0,0,0,.6)",     hi: "rgba(200,200,210,.4)" },
    donut:    { style: "donut",   color: "#F59AC4", rgb: "245,154,196", shade: "rgba(120,50,80,.5)", hi: "rgba(255,240,248,.8)" },
    wreath:   { style: "wreath",  color: "#3E7A2E", rgb: "90,160,70",   shade: "rgba(10,30,5,.6)",   hi: "rgba(200,240,170,.5)" },
    hula:     { style: "hula",    color: "#E8505B", rgb: "232,80,91",   shade: "rgba(60,10,20,.5)",  hi: "rgba(255,230,230,.8)" },
    snake:    { style: "snake",   color: "#5BA84A", rgb: "91,168,74",   shade: "rgba(10,40,5,.6)",   hi: "rgba(210,255,190,.6)" },
    neon:     { style: "neon",    color: "#FF4FB8", rgb: "255,79,184",  shade: "rgba(80,0,50,.6)",   hi: "rgba(255,220,240,.9)" },
    rainbow:  { style: "rainbow", color: "#F5D84A", rgb: "245,216,74",  shade: "rgba(60,40,0,.5)",   hi: "rgba(255,255,255,.8)" },
    halo:     { style: "halo",    color: "#F5D84A", rgb: "255,230,120", shade: "rgba(120,80,0,.5)",  hi: "rgba(255,255,230,.95)" },
    toilet:   { style: "toilet",  color: "#F4F4F0", rgb: "240,240,236", shade: "rgba(60,60,60,.45)", hi: "rgba(255,255,255,.95)" },
    vine:     { style: "vinering", color: "#5E7A36", rgb: "120,160,70",  shade: "rgba(10,20,5,.6)",   hi: "rgba(200,230,150,.5)" },
    nest:     { style: "nest",    color: "#8A6A3A", rgb: "160,120,70",  shade: "rgba(40,20,5,.6)",   hi: "rgba(230,200,150,.5)" },
    lifebuoy: { style: "lifebuoy", color: "#E8505B", rgb: "232,80,91",  shade: "rgba(60,10,20,.5)",  hi: "rgba(255,255,255,.9)" },
    saturn:   { style: "saturn",  color: "#E8C88A", rgb: "232,200,138", shade: "rgba(80,60,20,.5)",  hi: "rgba(255,245,220,.9)" }
  });
  const inkArc = (c, r, lw, col, w = 1) => { c.lineWidth = lw * 1.36 * w; c.strokeStyle = INK; c.beginPath(); c.arc(0, 0, r, 0, TAU); c.stroke(); c.lineWidth = lw * w; c.strokeStyle = col; c.beginPath(); c.arc(0, 0, r, 0, TAU); c.stroke(); };
  const RING_STYLES = {
    rope(c, x, y, r, lw, R) { c.save(); c.translate(x, y); inkArc(c, r, lw, R.color); c.strokeStyle = "#8A6A3A"; c.lineWidth = lw * 0.18; for (let i = 0; i < 28; i++) { const a = (i / 28) * TAU; c.beginPath(); c.moveTo(Math.cos(a) * (r - lw * 0.45), Math.sin(a) * (r - lw * 0.45)); c.lineTo(Math.cos(a + 0.1) * (r + lw * 0.45), Math.sin(a + 0.1) * (r + lw * 0.45)); c.stroke(); } c.restore(); },
    tire(c, x, y, r, lw) { c.save(); c.translate(x, y); inkArc(c, r, lw, "#2A2A2E", 1.35); c.fillStyle = "#4A4A52"; for (let i = 0; i < 20; i++) { const a = (i / 20) * TAU; c.save(); c.rotate(a); c.fillRect(r + lw * 0.35, -lw * 0.15, lw * 0.3, lw * 0.3); c.restore(); } c.strokeStyle = "#6A6A74"; c.lineWidth = lw * 0.12; c.beginPath(); c.arc(0, 0, r - lw * 0.35, 0, TAU); c.stroke(); c.restore(); },
    donut(c, x, y, r, lw, R) { c.save(); c.translate(x, y); inkArc(c, r, lw, "#D8A060", 1.5); c.lineWidth = lw * 1.1; c.strokeStyle = R.color; c.beginPath(); for (let i = 0; i <= 60; i++) { const a = (i / 60) * TAU, rr2 = r + Math.sin(a * 9) * lw * 0.12; i ? c.lineTo(Math.cos(a) * rr2, Math.sin(a) * rr2) : c.moveTo(Math.cos(a) * rr2, Math.sin(a) * rr2); } c.stroke(); const cols = [CREAM, TEAL, MUSTARD, "#7FC8E8"]; for (let i = 0; i < 22; i++) { const a = (i / 22) * TAU + (i % 3) * 0.1, rr2 = r + ((i * 7) % 5 - 2) * lw * 0.12; c.save(); c.translate(Math.cos(a) * rr2, Math.sin(a) * rr2); c.rotate(i * 1.3); c.fillStyle = cols[i % 4]; c.fillRect(-lw * 0.18, -lw * 0.05, lw * 0.36, lw * 0.1); c.restore(); } c.restore(); },
    wreath(c, x, y, r, lw) { c.save(); c.translate(x, y); inkArc(c, r, lw, "#2A5A20", 1.1); for (let i = 0; i < 18; i++) { const a = (i / 18) * TAU; c.save(); c.rotate(a); c.translate(r, 0); c.rotate(i % 2 ? 0.7 : -0.7); c.fillStyle = i % 2 ? "#3E7A2E" : "#4E8A38"; c.strokeStyle = INK; c.lineWidth = lw * 0.08; c.beginPath(); c.ellipse(0, 0, lw * 0.75, lw * 0.32, 0, 0, TAU); c.fill(); c.stroke(); c.restore(); } c.fillStyle = "#D02A2A"; for (let i = 0; i < 6; i++) { const a = (i / 6) * TAU + 0.3; for (const d of [0, 0.25]) { c.beginPath(); c.arc(Math.cos(a + d * 0.3) * r, Math.sin(a + d * 0.3) * r, lw * 0.2, 0, TAU); c.fill(); } } c.restore(); },
    hula(c, x, y, r, lw, R, t) { c.save(); c.translate(x, y); inkArc(c, r, lw, CREAM); const cols = ["#E8505B", "#F5D84A", "#4A8FD8", "#5BB86A"], n = 24, seg = TAU / n; c.lineWidth = lw; for (let i = 0; i < n; i++) { c.strokeStyle = cols[i % 4]; const a = i * seg + t * 0.8; c.beginPath(); c.arc(0, 0, r, a, a + seg * 0.55); c.stroke(); } c.restore(); },
    snake(c, x, y, r, lw, R, t) { c.save(); c.translate(x, y); c.rotate(t * 0.2); inkArc(c, r, lw, R.color, 1.1); c.fillStyle = "#3E7A2E"; for (let i = 0; i < 14; i++) { const a = (i / 14) * TAU; c.beginPath(); c.arc(Math.cos(a) * r, Math.sin(a) * r, lw * 0.18, 0, TAU); c.fill(); } c.fillStyle = R.color; c.strokeStyle = INK; c.lineWidth = lw * 0.12; c.beginPath(); c.ellipse(r, -lw * 0.2, lw * 0.9, lw * 0.6, -0.4, 0, TAU); c.fill(); c.stroke(); c.fillStyle = CREAM; c.beginPath(); c.arc(r + lw * 0.2, -lw * 0.5, lw * 0.18, 0, TAU); c.fill(); c.fillStyle = INK; c.beginPath(); c.arc(r + lw * 0.25, -lw * 0.5, lw * 0.08, 0, TAU); c.fill(); c.restore(); },
    neon(c, x, y, r, lw, R, t) { const on = (t % 3.7) < 0.08 ? 0.3 : 1; c.save(); c.translate(x, y); c.globalCompositeOperation = "lighter"; for (const [w, a] of [[4, 0.12], [2.4, 0.25]]) { c.lineWidth = lw * w; c.strokeStyle = `rgba(255,79,184,${a * on})`; c.beginPath(); c.arc(0, 0, r, 0, TAU); c.stroke(); } c.restore(); c.save(); c.translate(x, y); c.lineWidth = lw * 0.9; c.strokeStyle = on > 0.5 ? "#FFD6EE" : "#8A3A6A"; c.beginPath(); c.arc(0, 0, r, 0, TAU); c.stroke(); c.restore(); },
    rainbow(c, x, y, r, lw) { c.save(); c.translate(x, y); c.lineWidth = lw * 1.5; c.strokeStyle = INK; c.beginPath(); c.arc(0, 0, r, 0, TAU); c.stroke(); ["#E8505B", "#F5B83A", "#F5E84A", "#5BB86A", "#4A8FD8", "#8A6BC8"].forEach((col, i) => { c.lineWidth = lw * 0.2; c.strokeStyle = col; c.beginPath(); c.arc(0, 0, r - lw * 0.5 + i * lw * 0.2, 0, TAU); c.stroke(); }); c.restore(); },
    halo(c, x, y, r, lw, R, t) { c.save(); c.translate(x, y); c.globalCompositeOperation = "lighter"; const k = 0.8 + 0.2 * Math.sin(t * 3); for (const [w, a] of [[5, 0.1], [3, 0.2]]) { c.lineWidth = lw * w; c.strokeStyle = `rgba(255,230,120,${a * k})`; c.beginPath(); c.arc(0, 0, r, 0, TAU); c.stroke(); } c.restore(); c.save(); c.translate(x, y); inkArc(c, r, lw, "#F5D84A"); c.lineWidth = lw * 0.25; c.strokeStyle = "rgba(255,255,230,.9)"; c.beginPath(); c.arc(0, 0, r - lw * 0.15, Math.PI * 1.1, Math.PI * 1.7); c.stroke(); c.restore(); },
    toilet(c, x, y, r, lw) { c.save(); c.translate(x, y); c.scale(1, 1.12); inkArc(c, r, lw * 1.25, "#F4F4F0"); c.lineWidth = lw * 0.2; c.strokeStyle = "rgba(160,160,160,.5)"; c.beginPath(); c.arc(0, 0, r - lw * 0.3, 0.2, Math.PI - 0.2); c.stroke(); c.restore(); c.fillStyle = "#DADAD4"; c.strokeStyle = INK; c.lineWidth = Math.max(1.5, lw * 0.12); c.beginPath(); rr(c, x - r * 0.35, y - r * 1.12 - lw * 1.2, r * 0.7, lw * 0.9, lw * 0.3); c.fill(); c.stroke(); },
    vinering(c, x, y, r, lw, R, t) { c.save(); c.translate(x, y); inkArc(c, r, lw * 0.8, "#5E7A36"); c.strokeStyle = "#7F9447"; c.lineWidth = lw * 0.25; c.beginPath(); for (let i = 0; i <= 80; i++) { const a = (i / 80) * TAU, rr2 = r + Math.sin(a * 8) * lw * 0.3; i ? c.lineTo(Math.cos(a) * rr2, Math.sin(a) * rr2) : c.moveTo(Math.cos(a) * rr2, Math.sin(a) * rr2); } c.stroke(); for (let i = 0; i < 7; i++) { const a = (i / 7) * TAU + 0.2; c.save(); c.translate(Math.cos(a) * (r + lw * 0.5), Math.sin(a) * (r + lw * 0.5)); c.rotate(a + Math.sin(t * 2 + i) * 0.2); c.fillStyle = "#7F9447"; c.strokeStyle = INK; c.lineWidth = lw * 0.08; c.beginPath(); c.ellipse(lw * 0.4, 0, lw * 0.6, lw * 0.3, 0, 0, TAU); c.fill(); c.stroke(); c.restore(); } c.fillStyle = "#E07B2C"; c.beginPath(); c.arc(0, -r - lw * 0.5, lw * 0.5, 0, TAU); c.fill(); c.stroke(); c.restore(); },
    nest(c, x, y, r, lw) { c.save(); c.translate(x, y); inkArc(c, r, lw * 1.2, "#6A4A22"); c.strokeStyle = "#A8824A"; c.lineWidth = lw * 0.12; seeded(111, 40, rnd => { const a = rnd() * TAU, d = r + (rnd() - 0.5) * lw * 1.1, l = lw * (0.6 + rnd() * 0.8), b = a + Math.PI / 2 + (rnd() - 0.5); c.beginPath(); c.moveTo(Math.cos(a) * d - Math.cos(b) * l, Math.sin(a) * d - Math.sin(b) * l); c.lineTo(Math.cos(a) * d + Math.cos(b) * l, Math.sin(a) * d + Math.sin(b) * l); c.stroke(); }); c.fillStyle = "#BFE3DA"; c.strokeStyle = INK; c.lineWidth = lw * 0.1; c.beginPath(); c.ellipse(-r * 0.2, -r - lw * 0.3, lw * 0.35, lw * 0.45, 0.2, 0, TAU); c.fill(); c.stroke(); c.restore(); },
    lifebuoy(c, x, y, r, lw, R) { c.save(); c.translate(x, y); inkArc(c, r, lw * 1.35, CREAM); c.lineWidth = lw * 1.35; c.strokeStyle = R.color; for (let i = 0; i < 4; i++) { const a = i * Math.PI / 2 + Math.PI / 4; c.beginPath(); c.arc(0, 0, r, a - 0.3, a + 0.3); c.stroke(); } c.strokeStyle = "#C8A46A"; c.lineWidth = lw * 0.15; for (let i = 0; i < 4; i++) { const a = i * Math.PI / 2; c.beginPath(); c.arc(0, 0, r + lw * 0.65, a - 0.35, a + 0.35); c.stroke(); } c.restore(); },
    saturn(c, x, y, r, lw, R, t) { c.save(); c.translate(x, y); inkArc(c, r, lw, R.color); c.lineWidth = lw * 0.3; c.strokeStyle = "#B8986A"; c.beginPath(); c.arc(0, 0, r - lw * 0.25, 0, TAU); c.stroke(); c.save(); c.rotate(-0.35); c.scale(1, 0.28); c.lineWidth = lw * 0.9; c.strokeStyle = INK; c.beginPath(); c.arc(0, 0, r * 1.45, Math.PI * 0.05, Math.PI * 0.95); c.stroke(); c.lineWidth = lw * 0.55; c.strokeStyle = "#D8B87A"; c.beginPath(); c.arc(0, 0, r * 1.45, Math.PI * 0.05, Math.PI * 0.95); c.stroke(); c.restore(); c.fillStyle = "#FFFFFF"; for (let i = 0; i < 3; i++) { const a = t * 0.8 + i * 2.1; c.beginPath(); c.arc(Math.cos(a) * r * 1.6, Math.sin(a) * r * 0.4, lw * 0.15, 0, TAU); c.fill(); } c.restore(); }
  };

  // ── aim lines
  Object.assign(AIMS, {
    pink: { color: "#F59AC4" }, mint: { color: "#9FEFD0" }, ocean: { color: "#4A8FD8" },
    sunset: { color: "#F58A3A", hue: [330, 45] }, candy: { color: "#E8505B", alt: CREAM }, ghost: { color: "#EAF7F2", ghost: true },
    bones: { color: CREAM, shape: "bone" }, starry: { color: "#F5D84A", shape: "star" }
  });

  // ── trails and their particles
  Object.assign(TRAILS, {
    hearts: { line: "dots", color: "#E8505B", emit: "heart", rate: 0.35 },   leaves: { line: "none", emit: "leaf", rate: 0.4 },
    snow: { line: "dots", color: "#EAF4FA", emit: "snow", rate: 0.9 },       eyeballs: { line: "none", emit: "eyeball", rate: 0.22 },
    teeth: { line: "none", emit: "tooth", rate: 0.3 },                      candy: { line: "none", emit: "candy", rate: 0.3 },
    rainbow: { line: "rainbow", len: 20 },                                  slime: { line: "dots", color: "#8FD840", emit: "slime", rate: 0.7 },
    pixels: { line: "none", emit: "pixel", rate: 1.3 },                     rings: { line: "none", emit: "ring", rate: 0.16 },
    zzz: { line: "none", emit: "zzz", rate: 0.12 },                         tp: { line: "tp", len: 26 },
    feathers: { line: "dots", color: "#3A3A46", emit: "feather", rate: 0.3 }, seeds: { line: "none", emit: "seed", rate: 0.4 },
    coins: { line: "dots", color: GOLD, emit: "coin", rate: 0.4 },          cards: { line: "none", emit: "card", rate: 0.25 }
  });
  const BITS_X = {   // extra particles: how each one spawns (fields on top of the defaults) and how it's drawn
    heart:   { spawn: (U, r) => ({ vx: rand(-0.06, 0.06) * U, vy: -U * rand(0.06, 0.14), life: 1, size: Math.max(4, r * 0.4), color: "#E8505B", g: -0.05, a: 1 }),
               draw(c, p) { const s = p.size; c.fillStyle = p.color; c.strokeStyle = INK; c.lineWidth = 1; c.beginPath(); c.moveTo(p.x, p.y + s * 0.7); c.bezierCurveTo(p.x - s * 1.1, p.y - s * 0.1, p.x - s * 0.5, p.y - s * 0.9, p.x, p.y - s * 0.35); c.bezierCurveTo(p.x + s * 0.5, p.y - s * 0.9, p.x + s * 1.1, p.y - s * 0.1, p.x, p.y + s * 0.7); c.fill(); c.stroke(); } },
    leaf:    { spawn: (U, r) => ({ vx: rand(-0.15, 0.15) * U, vy: U * rand(0, 0.08), life: 1.3, size: Math.max(5, r * 0.5), color: ["#C8642A", "#E8A03A", "#A84A2A"][(Math.random() * 3) | 0], g: 0.15, a: 1 }),
               draw(c, p) { const s = p.size; c.save(); c.translate(p.x + Math.sin(p.rot * 2) * s, p.y); c.rotate(p.rot); c.fillStyle = p.color; c.strokeStyle = INK; c.lineWidth = 1; c.beginPath(); c.moveTo(0, -s); c.quadraticCurveTo(s * 0.7, 0, 0, s); c.quadraticCurveTo(-s * 0.7, 0, 0, -s); c.fill(); c.stroke(); c.beginPath(); c.moveTo(0, -s); c.lineTo(0, s * 1.2); c.stroke(); c.restore(); } },
    snow:    { spawn: (U, r) => ({ vx: rand(-0.05, 0.05) * U, vy: U * rand(0.02, 0.06), life: 1.1, size: rand(1.5, 3.2), color: "#FFFFFF", g: 0.05, a: 1 }),
               draw(c, p) { c.strokeStyle = p.color; c.lineWidth = 1; for (let k = 0; k < 3; k++) { const a = p.rot + k * Math.PI / 3; c.beginPath(); c.moveTo(p.x - Math.cos(a) * p.size, p.y - Math.sin(a) * p.size); c.lineTo(p.x + Math.cos(a) * p.size, p.y + Math.sin(a) * p.size); c.stroke(); } } },
    eyeball: { spawn: (U, r) => ({ vx: rand(-0.1, 0.1) * U, vy: -U * rand(0.02, 0.1), life: 0.9, size: Math.max(3, r * 0.3), color: CREAM, g: 0.5, a: 1 }),
               draw(c, p) { c.fillStyle = "#FBF4EE"; c.strokeStyle = INK; c.lineWidth = 1; c.beginPath(); c.arc(p.x, p.y, p.size, 0, TAU); c.fill(); c.stroke(); c.fillStyle = TEAL; c.beginPath(); c.arc(p.x + Math.cos(p.rot) * p.size * 0.4, p.y + Math.sin(p.rot) * p.size * 0.4, p.size * 0.45, 0, TAU); c.fill(); c.fillStyle = INK; c.beginPath(); c.arc(p.x + Math.cos(p.rot) * p.size * 0.45, p.y + Math.sin(p.rot) * p.size * 0.45, p.size * 0.2, 0, TAU); c.fill(); } },
    tooth:   { spawn: (U, r) => ({ vx: rand(-0.15, 0.15) * U, vy: -U * rand(0.05, 0.2), life: 0.9, size: Math.max(3, r * 0.3), color: CREAM, g: 0.9, a: 1 }),
               draw(c, p) { const s = p.size; c.save(); c.translate(p.x, p.y); c.rotate(p.rot); c.fillStyle = "#FBF9F4"; c.strokeStyle = INK; c.lineWidth = 1; c.beginPath(); c.moveTo(-s * 0.7, -s * 0.6); c.quadraticCurveTo(0, -s * 1.1, s * 0.7, -s * 0.6); c.lineTo(s * 0.5, s * 0.8); c.lineTo(s * 0.1, s * 0.2); c.lineTo(-s * 0.1, s * 0.2); c.lineTo(-s * 0.5, s * 0.8); c.closePath(); c.fill(); c.stroke(); c.restore(); } },
    candy:   { spawn: (U, r) => ({ vx: rand(-0.12, 0.12) * U, vy: -U * rand(0, 0.12), life: 1, size: Math.max(4, r * 0.35), color: [RED, TEAL, MUSTARD, PURPLE][(Math.random() * 4) | 0], g: 0.5, a: 1 }),
               draw(c, p) { const s = p.size; c.save(); c.translate(p.x, p.y); c.rotate(p.rot); c.fillStyle = p.color; c.strokeStyle = INK; c.lineWidth = 1; for (const sd of [-1, 1]) { c.beginPath(); c.moveTo(sd * s * 0.5, 0); c.lineTo(sd * s * 1.1, -s * 0.45); c.lineTo(sd * s * 1.1, s * 0.45); c.closePath(); c.fill(); c.stroke(); } c.beginPath(); c.ellipse(0, 0, s * 0.6, s * 0.45, 0, 0, TAU); c.fill(); c.stroke(); c.restore(); } },
    slime:   { spawn: (U, r) => ({ vx: 0, vy: U * 0.06, life: 0.7, size: Math.max(2, r * 0.18), color: "#8FD840", g: 1.1, a: 0.95 }),
               draw(c, p) { c.fillStyle = p.color; c.strokeStyle = "#2A4A10"; c.lineWidth = 1; c.beginPath(); c.moveTo(p.x, p.y - p.size * 1.6); c.quadraticCurveTo(p.x + p.size, p.y, p.x, p.y + p.size); c.quadraticCurveTo(p.x - p.size, p.y, p.x, p.y - p.size * 1.6); c.fill(); c.stroke(); } },
    pixel:   { spawn: (U, r) => ({ vx: rand(-0.08, 0.08) * U, vy: rand(-0.08, 0.08) * U, life: 0.6, size: rand(2, 4), color: ["#E8505B", "#5BC8E8", "#F5D84A", "#8FD840"][(Math.random() * 4) | 0], g: 0, a: 1 }),
               draw(c, p) { c.fillStyle = p.color; const s = Math.round(p.size); c.fillRect(Math.round(p.x) - s, Math.round(p.y) - s, s * 2, s * 2); } },
    ring:    { spawn: (U, r) => ({ vx: 0, vy: -U * 0.03, life: 1.2, size: Math.max(3, r * 0.3), grow: r * 0.8, color: "#B8B4AA", g: -0.05, a: 0.7 }),
               draw(c, p) { c.strokeStyle = p.color; c.lineWidth = Math.max(1.5, p.size * 0.25); c.beginPath(); c.ellipse(p.x, p.y, p.size, p.size * 0.55, 0, 0, TAU); c.stroke(); } },
    zzz:     { spawn: (U, r) => ({ vx: rand(-0.03, 0.03) * U, vy: -U * 0.08, life: 1.3, size: Math.max(6, r * 0.6), color: CREAM, g: -0.05, a: 1 }),
               draw(c, p) { c.font = `${Math.round(p.size * 1.6)}px ${DISPLAY}`; c.textAlign = "center"; c.lineWidth = 3; c.strokeStyle = INK; c.strokeText("Z", p.x, p.y); c.fillStyle = p.color; c.fillText("Z", p.x, p.y); } },
    seed:    { spawn: (U, r) => ({ vx: rand(-0.15, 0.15) * U, vy: -U * rand(0, 0.15), life: 1, size: Math.max(3, r * 0.3), color: "#F4E6BE", g: 0.8, a: 1 }),
               draw(c, p) { const s = p.size; c.save(); c.translate(p.x, p.y); c.rotate(p.rot); c.fillStyle = p.color; c.strokeStyle = INK; c.lineWidth = 1; c.beginPath(); c.moveTo(0, -s * 1.2); c.bezierCurveTo(s, -s * 0.5, s * 0.8, s, 0, s); c.bezierCurveTo(-s * 0.8, s, -s, -s * 0.5, 0, -s * 1.2); c.fill(); c.stroke(); c.restore(); } },
    coin:    { spawn: (U, r) => ({ vx: rand(-0.12, 0.12) * U, vy: -U * rand(0.05, 0.2), life: 1, size: Math.max(3, r * 0.32), color: GOLD, g: 0.9, a: 1 }),
               draw(c, p) { const w = Math.abs(Math.cos(p.rot * 1.5)) * p.size; c.fillStyle = GOLD; c.strokeStyle = "#7A5A10"; c.lineWidth = 1; c.beginPath(); c.ellipse(p.x, p.y, Math.max(0.8, w), p.size, 0, 0, TAU); c.fill(); c.stroke(); if (w > p.size * 0.5) { c.fillStyle = "#7A5A10"; c.font = `bold ${Math.round(p.size)}px sans-serif`; c.textAlign = "center"; c.textBaseline = "middle"; c.fillText("$", p.x, p.y + 0.5); } } },
    card:    { spawn: (U, r) => ({ vx: rand(-0.15, 0.15) * U, vy: -U * rand(0, 0.1), life: 1.1, size: Math.max(5, r * 0.45), color: CREAM, g: 0.3, a: 1 }),
               draw(c, p) { const s = p.size; c.save(); c.translate(p.x, p.y); c.rotate(p.rot); c.scale(Math.cos(p.rot * 1.3), 1); c.fillStyle = "#FBF9F4"; c.strokeStyle = INK; c.lineWidth = 1; c.beginPath(); rr(c, -s * 0.5, -s * 0.7, s, s * 1.4, s * 0.12); c.fill(); c.stroke(); c.fillStyle = (p.ph || 0) > 0.5 ? RED : INK; c.font = `bold ${Math.round(s * 0.8)}px sans-serif`; c.textAlign = "center"; c.textBaseline = "middle"; c.fillText((p.ph || 0) > 0.5 ? "♥" : "♠", 0, 0); c.restore(); } },
    drop:    { spawn: (U, r) => ({ vx: rand(-0.3, 0.3) * U, vy: -U * rand(0.2, 0.5), life: 0.7, size: rand(2, 4), color: "#7FC8E8", g: 1.3, a: 1 }),
               draw(c, p) { c.fillStyle = p.color; c.beginPath(); c.moveTo(p.x, p.y - p.size * 1.6); c.quadraticCurveTo(p.x + p.size, p.y, p.x, p.y + p.size); c.quadraticCurveTo(p.x - p.size, p.y, p.x, p.y - p.size * 1.6); c.fill(); } },
    qmark:   { spawn: (U, r) => ({ vx: rand(-0.2, 0.2) * U, vy: -U * rand(0.1, 0.3), life: 0.9, size: rand(6, 10), color: CREAM, g: 0.3, a: 1 }),
               draw(c, p) { c.font = `${Math.round(p.size * 1.6)}px ${DISPLAY}`; c.textAlign = "center"; c.lineWidth = 3; c.strokeStyle = INK; c.strokeText("?", p.x, p.y); c.fillStyle = p.color; c.fillText("?", p.x, p.y); } }
  };

  // ── impacts
  Object.assign(IMPACTS, {
    pow:     { word: "POW!",     fill: "#F5D84A", text: INK,   bits: "stars" },
    zonk:    { word: "ZONK!",    fill: "#7FC8E8", text: INK,   bits: "inkstars", shape: "rough" },
    boing:   { word: "BOING!",   fill: "#9BC53D", text: INK,   bits: "stars", shape: "cloud" },
    thwack:  { word: "THWACK!",  fill: CREAM,     text: RED,   bits: "bones", shape: "rough" },
    sploosh: { word: "SPLOOSH!", fill: "#4A8FD8", text: CREAM, bits: "drop", shape: "splat" },
    zap:     { word: "ZAP!",     fill: "#F5E84A", text: INK,   bits: "spark" },
    blammo:  { word: "BLAMMO!",  fill: RED,       text: "#F5E84A", bits: "smoke", shape: "cloud", big: 1.15 },
    whoops:  { word: "WHOOPS!",  fill: PAPER,     text: INK,   bits: "qmark", shape: "news" },
    caw:     { word: "CAW!",     fill: "#3A3A46", text: CREAM, bits: "feather" },
    squash:  { word: "SQUASH!",  fill: "#E07B2C", text: INK,   bits: "chunk", shape: "splat" },
    kapow:   { word: "KA-POW!",  fill: GOLD,      text: RED,   bits: "coin", big: 1.2 }
  });

  // ── film reels: the look of the whole print (a CSS filter on the play field)
  const REEL_FRAME = { noir: ["#111", "#EEE"], cyan: ["#1A3A6A", "#9AC8E8"], infra: ["#5A1020", "#F0A0B0"], twostrip: ["#3A5A5A", "#E88A6A"], bootleg: ["#2A2A40", "#C8A0E8"] };

  // ── ring poles (drawn from under the ring down to the ground)
  const woodPost = (c, x, top, bot, pw, col = "#6B4526") => { c.fillStyle = INK; c.fillRect(x - pw / 2 - 1.5, top, pw + 3, bot - top); c.fillStyle = col; c.fillRect(x - pw / 2, top, pw, bot - top); c.fillStyle = "rgba(242,231,201,.18)"; c.fillRect(x - pw / 2, top, Math.max(1, pw * 0.3), bot - top); };
  const footing = (c, x, bot, s, col = "#4A2F19") => { const cw = 0.36 * s, ch = 0.1 * s; c.fillStyle = col; c.strokeStyle = INK; c.lineWidth = 1.5; c.beginPath(); rr(c, x - cw / 2, bot - ch, cw, ch * 1.25, ch * 0.4); c.fill(); c.stroke(); };
  const stripes = (c, x, top, bot, pw, a, b, t = 0, slope = 1) => { c.save(); c.beginPath(); c.rect(x - pw / 2, top, pw, bot - top); c.clip(); c.fillStyle = a; c.fillRect(x - pw / 2, top, pw, bot - top); c.fillStyle = b; const st = pw * 1.4; for (let y = top - pw * 2 + ((t * 30) % st); y < bot + pw; y += st) { c.beginPath(); c.moveTo(x - pw / 2, y); c.lineTo(x + pw / 2, y - pw * slope); c.lineTo(x + pw / 2, y - pw * slope + st * 0.5); c.lineTo(x - pw / 2, y + st * 0.5); c.closePath(); c.fill(); } c.restore(); c.strokeStyle = INK; c.lineWidth = 1.5; c.strokeRect(x - pw / 2, top, pw, bot - top); };
  const POLES = {
    wood: null,
    totem: { draw(c, x, top, bot, pw, s, t) {   // v50 (the Cart): a totem pole, three faces stacked, wings at the top
      const w = pw * 2.4, n = 3, hh = (bot - top) / n;
      for (let i = 0; i < n; i++) { const y0 = top + i * hh, col = ["#B8322A", "#2F6FD0", "#3E7A2E"][i];
        c.fillStyle = INK; c.fillRect(x - w / 2 - 1.5, y0, w + 3, hh); c.fillStyle = "#8A5A30"; c.fillRect(x - w / 2, y0, w, hh);
        c.fillStyle = col; c.fillRect(x - w / 2, y0 + hh * 0.08, w, hh * 0.14);
        for (const sd of [-1, 1]) { c.fillStyle = "#F4ECD8"; c.beginPath(); c.ellipse(x + sd * w * 0.22, y0 + hh * 0.38, w * 0.14, hh * 0.08, 0, 0, TAU); c.fill(); c.fillStyle = INK; c.beginPath(); c.arc(x + sd * w * 0.22, y0 + hh * 0.38, Math.max(1, w * 0.06), 0, TAU); c.fill(); }
        c.fillStyle = INK; c.beginPath(); rr(c, x - w * 0.28, y0 + hh * 0.62, w * 0.56, hh * 0.12, 2); c.fill(); c.fillStyle = "#F4ECD8"; for (let k = -1; k <= 1; k++) c.fillRect(x + k * w * 0.14 - w * 0.04, y0 + hh * 0.62, w * 0.08, hh * 0.05); }
      c.fillStyle = "#E3B64B"; c.strokeStyle = INK; c.lineWidth = 1.5; for (const sd of [-1, 1]) { c.beginPath(); c.moveTo(x + sd * w * 0.5, top + hh * 0.1); c.lineTo(x + sd * w * 1.5, top - hh * 0.05 + Math.sin(t * 2) * 1.5); c.lineTo(x + sd * w * 0.5, top + hh * 0.35); c.closePath(); c.fill(); c.stroke(); }
      footing(c, x, bot, s, "#5A3A22");
    } },
    birch: { draw(c, x, top, bot, pw, s) { woodPost(c, x, top, bot, pw * 1.1, "#EDE6D6"); c.fillStyle = INK; seeded(121, 8, rnd => c.fillRect(x - pw * 0.55 + rnd() * pw * 0.4, top + rnd() * (bot - top), pw * (0.3 + rnd() * 0.4), 1.5)); footing(c, x, bot, s, "#6B6A5A"); } },
    bamboo: { draw(c, x, top, bot, pw, s) { woodPost(c, x, top, bot, pw * 1.1, "#9AB85A"); c.fillStyle = "#5E7A36"; for (let y = top + pw * 3; y < bot; y += pw * 4) c.fillRect(x - pw * 0.6, y, pw * 1.2, Math.max(2, pw * 0.3)); footing(c, x, bot, s); } },
    candy: { draw(c, x, top, bot, pw, s, t) { stripes(c, x, top, bot, pw * 1.2, "#FBF9F4", RED, 0); footing(c, x, bot, s, RED); } },
    barber: { draw(c, x, top, bot, pw, s, t) { stripes(c, x, top, bot, pw * 1.4, "#FBF9F4", RED, t); c.fillStyle = "#4A8FD8"; for (const y of [top, bot - pw * 1.2]) { c.beginPath(); rr(c, x - pw, y, pw * 2, pw * 1.2, pw * 0.3); c.fill(); c.strokeStyle = INK; c.lineWidth = 1.5; c.stroke(); } } },
    rake: { draw(c, x, top, bot, pw, s) { woodPost(c, x, top, bot - pw * 3, pw * 0.8, "#A87A48"); c.strokeStyle = INK; c.lineWidth = Math.max(2, pw * 0.4); c.beginPath(); c.moveTo(x - pw * 3, bot - pw * 3); c.lineTo(x + pw * 3, bot - pw * 3); for (let k = -3; k <= 3; k++) { c.moveTo(x + k * pw, bot - pw * 3); c.lineTo(x + k * pw, bot); } c.stroke(); c.strokeStyle = "#8E949F"; c.lineWidth = Math.max(1, pw * 0.2); c.stroke(); } },
    bones: { draw(c, x, top, bot, pw, s) { const h = pw * 5; for (let y = top; y < bot - pw * 1.6; y += h) { const y1 = Math.min(bot, y + h); c.fillStyle = CREAM; c.strokeStyle = INK; c.lineWidth = 1.5; c.beginPath(); rr(c, x - pw * 0.45, y + pw * 0.4, pw * 0.9, y1 - y - pw * 0.8, pw * 0.3); c.fill(); c.stroke(); for (const yy of [y + pw * 0.5, y1 - pw * 0.5]) for (const sd of [-1, 1]) { c.beginPath(); c.arc(x + sd * pw * 0.45, yy, pw * 0.42, 0, TAU); c.fill(); c.stroke(); } } } },
    lamp: { draw(c, x, top, bot, pw, s, t) { woodPost(c, x, top, bot, pw * 0.8, "#2A2E36"); c.save(); c.translate(x, top + (bot - top) * 0.25); c.fillStyle = "#2A2E36"; c.fillRect(0, -pw * 0.3, pw * 3, pw * 0.6); c.globalCompositeOperation = "lighter"; const g = c.createRadialGradient(pw * 3, pw * 1.2, 0, pw * 3, pw * 1.2, pw * 6); g.addColorStop(0, `rgba(255,210,120,${0.5 + 0.1 * Math.sin(t * 9)})`); g.addColorStop(1, "rgba(255,210,120,0)"); c.fillStyle = g; c.beginPath(); c.arc(pw * 3, pw * 1.2, pw * 6, 0, TAU); c.fill(); c.globalCompositeOperation = "source-over"; c.fillStyle = "#FFD27A"; c.strokeStyle = INK; c.lineWidth = 1.5; c.beginPath(); c.moveTo(pw * 2.3, 0); c.lineTo(pw * 3.7, 0); c.lineTo(pw * 3.4, pw * 2); c.lineTo(pw * 2.6, pw * 2); c.closePath(); c.fill(); c.stroke(); c.restore(); footing(c, x, bot, s, "#2A2E36"); } },
    pitchfork: { draw(c, x, top, bot, pw, s) { woodPost(c, x, top + pw * 4, bot, pw * 0.8, "#8A5A30"); c.strokeStyle = INK; c.lineWidth = Math.max(3, pw * 0.5); c.beginPath(); c.moveTo(x - pw * 1.6, top); c.lineTo(x - pw * 1.6, top + pw * 3); c.quadraticCurveTo(x - pw * 1.6, top + pw * 4, x, top + pw * 4); c.quadraticCurveTo(x + pw * 1.6, top + pw * 4, x + pw * 1.6, top + pw * 3); c.lineTo(x + pw * 1.6, top); c.moveTo(x, top); c.lineTo(x, top + pw * 4); c.stroke(); c.strokeStyle = "#9AA4AE"; c.lineWidth = Math.max(1.5, pw * 0.25); c.stroke(); } },
    broom: { draw(c, x, top, bot, pw, s) { woodPost(c, x, top, bot - pw * 5, pw * 0.8, "#8A5A30"); c.fillStyle = "#D8B048"; c.strokeStyle = INK; c.lineWidth = 1.5; c.beginPath(); c.moveTo(x - pw * 0.6, bot - pw * 5); c.lineTo(x + pw * 0.6, bot - pw * 5); c.lineTo(x + pw * 2.6, bot); c.lineTo(x - pw * 2.6, bot); c.closePath(); c.fill(); c.stroke(); c.strokeStyle = "rgba(90,60,10,.6)"; for (let k = -2; k <= 2; k++) { c.beginPath(); c.moveTo(x + k * pw * 0.2, bot - pw * 4.6); c.lineTo(x + k * pw * 1, bot); c.stroke(); } c.fillStyle = RED; c.fillRect(x - pw * 0.8, bot - pw * 5.2, pw * 1.6, pw * 0.6); } },
    neon: { draw(c, x, top, bot, pw, s, t) { c.save(); c.globalCompositeOperation = "lighter"; c.fillStyle = "rgba(127,246,255,.25)"; c.fillRect(x - pw * 1.5, top, pw * 3, bot - top); c.restore(); c.fillStyle = "#D8FCFF"; c.fillRect(x - pw * 0.35, top, pw * 0.7, bot - top); footing(c, x, bot, s, "#1A2A33"); } },
    column: { draw(c, x, top, bot, pw, s) { const w = pw * 2.2; c.fillStyle = "#EDEAE3"; c.strokeStyle = INK; c.lineWidth = 1.5; c.fillRect(x - w / 2, top + pw, w, bot - top - pw * 2); c.strokeRect(x - w / 2, top + pw, w, bot - top - pw * 2); c.strokeStyle = "rgba(120,115,105,.5)"; for (let k = -1; k <= 1; k++) { c.beginPath(); c.moveTo(x + k * w * 0.28, top + pw * 1.5); c.lineTo(x + k * w * 0.28, bot - pw * 1.5); c.stroke(); } c.fillStyle = "#DAD6CC"; c.strokeStyle = INK; for (const y of [top, bot - pw * 1.2]) { c.beginPath(); rr(c, x - w * 0.8, y, w * 1.6, pw * 1.2, pw * 0.3); c.fill(); c.stroke(); } } },
    skulls: { draw(c, x, top, bot, pw, s, t) { const r = pw * 1.3; for (let y = bot - r * 1.2, i = 0; y > top + r * 0.3; y -= r * 2.1, i++) drawSkull(c, x, y, r, { t: t + i, look: { ...DEFAULT_COS, skull: i % 2 ? "stone" : "bone" }, face: faceFor(i % 3 ? "idle" : "deadpan", t + i * 1.3) }); } },
    chain: { hang: true, draw(c, x, top, bot, pw, s, t, ringTop) { const y0 = -20; for (let y = ringTop; y > y0; y -= pw * 1.6) { c.strokeStyle = INK; c.lineWidth = Math.max(2, pw * 0.5); c.beginPath(); c.ellipse(x, y, pw * 0.5, pw * 0.9, 0, 0, TAU); c.stroke(); c.strokeStyle = "#9AA4AE"; c.lineWidth = Math.max(1, pw * 0.25); c.stroke(); } } },
    balloons: { hang: true, draw(c, x, top, bot, pw, s, t, ringTop) { const cols = [RED, TEAL, MUSTARD]; cols.forEach((col, i) => { const bx = x + (i - 1) * pw * 5 + Math.sin(t * 1.5 + i) * pw, by = ringTop - pw * (16 + (i % 2) * 4); c.strokeStyle = "rgba(242,231,201,.7)"; c.lineWidth = 1; c.beginPath(); c.moveTo(x, ringTop); c.quadraticCurveTo((x + bx) / 2, by + pw * 6, bx, by + pw * 3.4); c.stroke(); c.fillStyle = col; c.strokeStyle = INK; c.lineWidth = 1.5; c.beginPath(); c.ellipse(bx, by, pw * 2.6, pw * 3.3, 0, 0, TAU); c.fill(); c.stroke(); c.fillStyle = "rgba(255,255,255,.4)"; c.beginPath(); c.ellipse(bx - pw * 0.9, by - pw * 1.2, pw * 0.5, pw * 0.9, -0.5, 0, TAU); c.fill(); }); } },
    tentacle: { draw(c, x, top, bot, pw, s, t) { c.lineCap = "round"; for (const [col, w] of [[INK, 1.6], ["#8A4AA0", 1.2]]) { c.strokeStyle = col; c.beginPath(); const n = 12; for (let i = 0; i <= n; i++) { const k = i / n, y = bot - (bot - top) * k, xx = x + Math.sin(t * 2.5 + k * 5) * pw * 1.5 * k; c.lineWidth = pw * w * (1.6 - k * 0.8); i ? c.lineTo(xx, y) : c.moveTo(xx, y); } c.stroke(); } c.fillStyle = "#E8B8F0"; for (let i = 1; i < 10; i++) { const k = i / 10, y = bot - (bot - top) * k, xx = x + Math.sin(t * 2.5 + k * 5) * pw * 1.5 * k; c.beginPath(); c.arc(xx + pw * 0.5, y, pw * 0.25 * (1.4 - k), 0, TAU); c.fill(); } c.lineCap = "butt"; } },
    plunger: { draw(c, x, top, bot, pw, s) { woodPost(c, x, top, bot - pw * 3, pw * 1.1, "#A87A48"); c.fillStyle = "#C0382A"; c.strokeStyle = INK; c.lineWidth = 1.5; c.beginPath(); c.moveTo(x - pw * 0.8, bot - pw * 3.2); c.quadraticCurveTo(x - pw * 3.4, bot - pw * 2.6, x - pw * 3.2, bot); c.lineTo(x + pw * 3.2, bot); c.quadraticCurveTo(x + pw * 3.4, bot - pw * 2.6, x + pw * 0.8, bot - pw * 3.2); c.closePath(); c.fill(); c.stroke(); } },
    vine: { draw(c, x, top, bot, pw, s, t) { c.lineCap = "round"; for (const [col, w] of [[INK, 1.5], ["#5E7A36", 1.05]]) { c.strokeStyle = col; c.lineWidth = pw * w; c.beginPath(); for (let i = 0; i <= 16; i++) { const k = i / 16, y = bot - (bot - top) * k, xx = x + Math.sin(k * 9) * pw * 0.8; i ? c.lineTo(xx, y) : c.moveTo(xx, y); } c.stroke(); } for (let i = 1; i < 6; i++) { const k = i / 6, y = bot - (bot - top) * k, xx = x + Math.sin(k * 9) * pw * 0.8, sd = i % 2 ? 1 : -1; c.fillStyle = "#7F9447"; c.strokeStyle = INK; c.lineWidth = 1.2; c.beginPath(); c.ellipse(xx + sd * pw * 1.4, y, pw * 1.4, pw * 0.6, sd * (0.4 + Math.sin(t * 2 + i) * 0.15), 0, TAU); c.fill(); c.stroke(); } c.lineCap = "butt"; } },
    perch: { draw(c, x, top, bot, pw, s, t) { woodPost(c, x, top, bot, pw * 1.1, "#4A3A2A"); c.strokeStyle = INK; c.lineWidth = pw * 0.7; c.beginPath(); c.moveTo(x, top + (bot - top) * 0.4); c.lineTo(x + pw * 4, top + (bot - top) * 0.3); c.stroke(); c.strokeStyle = "#4A3A2A"; c.lineWidth = pw * 0.4; c.stroke();
      const bx = x + pw * 3.4, by = top + (bot - top) * 0.3 - pw * 1.4; c.fillStyle = "#2B2B33"; c.strokeStyle = INK; c.lineWidth = 1.2; c.beginPath(); c.ellipse(bx, by, pw * 1.1, pw * 1.4, 0, 0, TAU); c.fill(); c.stroke(); c.fillStyle = CREAM; c.beginPath(); c.arc(bx + pw * 0.35, by - pw * 0.4, pw * 0.35, 0, TAU); c.fill(); c.fillStyle = INK; c.beginPath(); c.arc(bx + pw * 0.45, by - pw * 0.4, pw * 0.16, 0, TAU); c.fill(); c.fillStyle = GOLD; c.beginPath(); c.moveTo(bx + pw * 0.9, by - pw * 0.2); c.lineTo(bx + pw * 1.8, by); c.lineTo(bx + pw * 0.9, by + pw * 0.2); c.fill(); } },
    gold: { draw(c, x, top, bot, pw, s, t) { woodPost(c, x, top, bot, pw * 1.2, GOLD); glintAt2(c, x, top + (bot - top) * 0.3, pw * 3, Math.pow(Math.max(0, Math.sin(t * 2)), 10)); footing(c, x, bot, s, "#B8862A"); } },
    rocket: { draw(c, x, top, bot, pw, s, t) { const w = pw * 2.4, bodyTop = top + pw * 2, bodyBot = bot - pw * 5; c.fillStyle = "#EDEAE3"; c.strokeStyle = INK; c.lineWidth = 1.5; c.beginPath(); c.moveTo(x, top); c.quadraticCurveTo(x + w * 0.6, bodyTop, x + w / 2, bodyBot); c.lineTo(x - w / 2, bodyBot); c.quadraticCurveTo(x - w * 0.6, bodyTop, x, top); c.fill(); c.stroke(); c.fillStyle = RED; for (const sd of [-1, 1]) { c.beginPath(); c.moveTo(x + sd * w / 2, bodyBot - pw * 3); c.lineTo(x + sd * w * 1.1, bodyBot + pw); c.lineTo(x + sd * w / 2, bodyBot); c.closePath(); c.fill(); c.stroke(); } c.fillStyle = "#7FC8E8"; c.beginPath(); c.arc(x, bodyTop + pw * 3, pw * 0.8, 0, TAU); c.fill(); c.stroke();
      const fl = 0.7 + 0.3 * Math.sin(t * 30); c.fillStyle = "#F5B83A"; c.beginPath(); c.moveTo(x - w * 0.4, bodyBot); c.quadraticCurveTo(x, bot + pw * 2 * fl, x + w * 0.4, bodyBot); c.fill(); c.fillStyle = "#FFF3C0"; c.beginPath(); c.moveTo(x - w * 0.2, bodyBot); c.quadraticCurveTo(x, bot - pw * 1.5 * fl, x + w * 0.2, bodyBot); c.fill(); } }
  };
  function glintAt2(c, x, y, r, k) { if (k < 0.03) return; c.fillStyle = `rgba(255,252,236,${k})`; star(c, x, y, r * k, 4, 0.18, 0); c.fill(); }

  // ── v45: the Can Alley prizes (07o_bonus.js), one for the first clear after each end boss but the last
  // v50 (the Cart): a Ferris wheel for a ring — spokes, and the cars swinging on the rim as it turns
  Object.assign(RINGS, { ferris: { style: "ferris", color: "#E8505B", rgb: "232,80,91", shade: "rgba(60,10,20,.5)", hi: "rgba(255,240,220,.9)" } });
  RING_STYLES.ferris = (c, x, y, r, lw, R, t) => {
    c.save(); c.translate(x, y); inkArc(c, r, lw * 0.8, R.color); c.rotate(t * 0.3);
    c.strokeStyle = "rgba(242,231,201,.55)"; c.lineWidth = Math.max(1, lw * 0.12); for (let i = 0; i < 8; i++) { const a = (i / 8) * TAU; c.beginPath(); c.moveTo(Math.cos(a) * r * 0.2, Math.sin(a) * r * 0.2); c.lineTo(Math.cos(a) * (r - lw * 0.4), Math.sin(a) * (r - lw * 0.4)); c.stroke(); }
    const cols = ["#F5D84A", "#4A8FD8", "#5BB86A", "#F58A3A"];
    for (let i = 0; i < 8; i++) { const a = (i / 8) * TAU, cx = Math.cos(a) * r, cy = Math.sin(a) * r; c.save(); c.translate(cx, cy); c.rotate(-t * 0.3); c.fillStyle = cols[i % 4]; c.strokeStyle = INK; c.lineWidth = Math.max(1, lw * 0.1); c.beginPath(); rr(c, -lw * 0.45, lw * 0.2, lw * 0.9, lw * 0.6, lw * 0.15); c.fill(); c.stroke(); c.restore(); }
    c.fillStyle = "#FFF3C0"; for (let i = 0; i < 16; i++) { const a = (i / 16) * TAU + 0.2; if ((Math.floor(t * 4) + i) % 3) continue; c.beginPath(); c.arc(Math.cos(a) * r, Math.sin(a) * r, lw * 0.14, 0, TAU); c.fill(); }
    c.restore();
  };
  Object.assign(RINGS, { bigtop: { style: "bigtop", color: "#C8503A", rgb: "200,80,58", shade: "rgba(70,14,8,.6)", hi: "rgba(255,240,220,.85)" } });
  Object.assign(RING_STYLES, {
    bigtop(c, x, y, r, lw, R, t) {   // a big-top stripe, red and cream, with a run of marquee bulbs round the outside
      c.save(); c.translate(x, y); inkArc(c, r, lw * 1.2, CREAM); const n = 20, seg = TAU / n; c.lineWidth = lw * 1.2; c.strokeStyle = R.color;
      for (let i = 0; i < n; i += 2) { c.beginPath(); c.arc(0, 0, r, i * seg, (i + 1) * seg); c.stroke(); }
      for (let i = 0; i < 16; i++) { const a = (i / 16) * TAU, on = (Math.floor(t * 4) + i) % 2, bx = Math.cos(a) * (r + lw * 0.95), by = Math.sin(a) * (r + lw * 0.95);
        c.fillStyle = on ? "#FFE36A" : "#B8862A"; c.strokeStyle = INK; c.lineWidth = Math.max(1, lw * 0.14); c.beginPath(); c.arc(bx, by, Math.max(1.4, lw * 0.26), 0, TAU); c.fill(); c.stroke(); }
      c.restore();
    }
  });
  Object.assign(AIMS, { tickets: { color: "#E8505B", alt: "#F5D84A", shape: "star" } });
  Object.assign(TRAILS, { midway: { line: "dots", color: "#F5D84A", emit: "confetti", rate: 1.4 } });
  Object.assign(IMPACTS, { ringer: { word: "RINGER!", fill: "#E8505B", text: CREAM, bits: "confetti" } });
  Object.assign(AURAS, { bulbs: { twinkle: 12, cols: ["#FFE36A", "#FFB43A", "#FFFFFF"] } });
  Object.assign(HATS, {
    tincan(c) {   // a tin can worn as a top hat, skull on the label, its lid still hanging on
      const lw = c.lineWidth; c.fillStyle = "#B8BCC4"; c.beginPath(); c.rect(-0.46, -1.62, 0.92, 0.76); c.fill(); c.stroke();
      c.fillStyle = "#C8503A"; c.fillRect(-0.46, -1.42, 0.92, 0.36); c.strokeRect(-0.46, -1.42, 0.92, 0.36);
      c.fillStyle = CREAM; c.beginPath(); c.arc(0, -1.26, 0.1, 0, TAU); c.fill(); c.fillRect(-0.06, -1.2, 0.12, 0.07);
      c.strokeStyle = "rgba(23,19,15,.45)"; c.lineWidth = 0.025; for (const yy of [-1.52, -0.96]) { c.beginPath(); c.moveTo(-0.46, yy); c.lineTo(0.46, yy); c.stroke(); }
      c.strokeStyle = INK; c.lineWidth = lw; c.fillStyle = "#D8DCE2"; c.beginPath(); c.ellipse(0, -1.62, 0.46, 0.1, 0, 0, TAU); c.fill(); c.stroke();
      c.save(); c.translate(0.46, -1.62); c.rotate(-0.9); c.beginPath(); c.ellipse(0.3, 0, 0.3, 0.08, 0, 0, TAU); c.fill(); c.stroke(); c.restore();
    }
  });
